language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install --prefix client
  - npm run test --prefix client
  - npm run lint --prefix client
  - npm rebuild node-sass --prefix client
  - npm run build --prefix client
  - npm run build